version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: tartmysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: tartrdb
    ports:
      - "6379:6379"
    networks:
      - app-network

  web:
    image: tart-shop-manager-go
    container_name: webapp
    environment:
      REDIS_URL: ${REDIS_URL}
      MYSQL_URL: ${MYSQL_URL}
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
